version: '3.9'
services:
  db:
    image: mysql
    volumes:
      - /opt/homebrew/var/mysql
    environment:
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
  rails:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - .:/backend
    ports:
      - 5000:5000
    depends_on:
      - db
  vue:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - .:/front
    ports:
      - 3000:3000
    depends_on:
      - db
