version: '3.9'
services:
  db:
    image: mysql
    volumes:
      - ./mysql-store:/var/lib/mysql
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
  rails:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    image: rails
    volumes:
      - ./backend:/backend
    ports:
      - 4000:4000
    links:
      - db:mysql
  vue:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    command: bash -c "yarn dev && /bin/bash"
    image: vue
    tty: true
    volumes:
      - ./front:/front
    ports:
      - 3000:3000
    links:
      - db:mysql
